import { useEffect, useState } from "react";

import Head from "next/head";

import styles from "../styles/Home.module.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

export default function Home() {
  const [games, setGames] = useState([]);

  useEffect(() => {
    const fetchGames = async () => {
      const response = await fetch(
        "https://projectyquebec.azurewebsites.net/api/v1/Product/all"
      );
      const data = await response.json();
      setGames(data);
    };

    fetchGames();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1>Project Y</h1>

        {games.map((game) => (
          <div key={game.name}>{game.name}</div>
        ))}
      </main>
    </div>
  );
}
