import Head from "next/head";
import styles from "../styles/Home.module.css";

import useFetchGames from "../hooks/useFetchGames";

export default function Home() {
  const { games, isLoading, isError } = useFetchGames();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1>Project Y</h1>

        {isLoading ? (
          <p>Loading...</p>
        ) : isError ? (
          <p>Error...</p>
        ) : (
          games?.map((game) => <div key={game.name}>{game.name}</div>)
        )}
      </main>
    </div>
  );
}
