import Head from "next/head";

import useFetchGames from "../hooks/useFetchGames";
import Layout from "../components/layout/layout";

export default function Home() {
  const { games, isLoading, isError } = useFetchGames();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        {/* TODO: Move that at the good place, see console error */}
        {/*<link*/}
        {/*  rel="stylesheet"*/}
        {/*  href="https://fonts.googleapis.com/icon?family=Material+Icons"*/}
        {/*/>*/}
      </Head>

      <main>
        {isLoading ? (
          <p>Loading...</p>
        ) : isError ? (
          <p>Error...</p>
        ) : (
          games?.map((game) => <div key={game.name}>{game.name}</div>)
        )}
      </main>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      <div>{page}</div>
    </Layout>
  );
};
